import os
import json
import re
import subprocess
import time

from flask import jsonify, request
import shutil
from ..app import app

BASE_DIR = os.path.dirname(os.path.abspath(__file__))                      # base project directory
# every controller directory
INVENTORY_DIR = os.path.join(BASE_DIR, "inventories")
CONTROLLER_PLAYBOOKS_DIR = os.path.join(BASE_DIR, "controllerPlaybooks")
CONTROLLER_CONFIGS_DIR = os.path.join(BASE_DIR, "controllerConfigs")
USER_PLAYBOOKS_DIR = os.path.join(BASE_DIR, "userPlaybooks")
USER_CONFIGS_DIR = os.path.join(BASE_DIR, "userConfigs")
SNAPSHOTS_DIR = os.path.join(BASE_DIR, "snapshots")
TEMPLATES_DIR = os.path.join(CONTROLLER_PLAYBOOKS_DIR, "templates")
WRAPPERS_DIR = os.path.join(CONTROLLER_PLAYBOOKS_DIR, "wrappers")
# playbook template schema
INPUT_TEMPLATE_CONTENT = r"""- name: Apply per-host commands
  hosts: all
  gather_facts: no
  vars:
    commands_map:
      # insert a list of commands after each device

  tasks:
    - name: Run commands from commands_map
      vars:
        cmds: "{{ commands_map[inventory_hostname] | default([]) | map('regex_replace', '^\\s*sudo\\s+', 'sudo -n ') | list}}"
      ansible.builtin.shell: |
        {% for c in cmds %}
        {{ c }}
        {% endfor %}
      when: commands_map[inventory_hostname] is defined and (commands_map[inventory_hostname] | length > 0)  
"""

ANSIBLE_EXTRA_ARGS = ""            #  extra args (ex. -c paramiko)
# default credentials per role
SONIC_USER = "admin"
SONIC_PASS = "YourPaSsWoRd"
MINIPC_USER = "oem"
MINIPC_PASS = "oem123"
active_reservations = {}    # dictionary that contains active and usable (after key insertion) reservation
TEST = True                 # if true uses wsl on windows (/mnt), otherwise normal paths

def safe_filename(name: str) -> str:
    # sanitize a string for use as filename
    s = str(name or "")
    s = re.sub(r"[^\w\-.]", "_", s) #find each character which is not letter, number, _ , - or . and change them into _
    return s

def ensure_inventory_dir():
    # ensure existence of inventory directory
    os.makedirs(INVENTORY_DIR, exist_ok=True)
    return INVENTORY_DIR

def get_playbook_template_path(kind: str):
    """
    Return the path of playbook template for 'grant' or 'revoke' in the folder INVENTORY_DIR, None otherwise.
      - grant  -> <CONTROLLER_PLAYBOOKS_DIR>/grant_playbook.yml
      - revoke -> <CONTROLLER_PLAYBOOKS_DIR>/revoke_playbook.yml
    """
    kind = (kind or "").lower()
    # check playbook type
    if kind == "grant":
        filename = "grant_playbook.yml"
    elif kind == "revoke":
        filename = "revoke_playbook.yml"
    else:
        return None

    path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, filename)
    return path if os.path.exists(path) else None

def write_inventory(reservation_id: int, devices: list):
    """
    Create INI inventory file with hosts that have ip_device not None.
    devices: list of dict {"id_device", "ip_device", "role"}
    Returns path to inventory file and list of hostnames written.
    """
    inv_dir = ensure_inventory_dir()
    safe_res = safe_filename(f"res-{reservation_id}-inventory")
    inv_path = os.path.join(inv_dir, f"{safe_res}.ini")

    hosts_written = []
    #write inventory
    with open(inv_path, "w", encoding="utf-8") as fh:
        fh.write("# Inventory generated by controller\n")
        fh.write("[all]\n")
        for d in devices:
            asset = d.get("id_device")
            role = (d.get("role") or "").lower()
            ip = d.get("ip_device")
            interface = d.get("interface")
            if not ip:
                print("Skipping device without IP:", asset)
                continue
            # if asset tag missing, take the ip and change . with _ to create a valid string
            host_key = safe_filename(asset) if asset else ip.replace(".", "_")

            # pick credentials depending on role
            if role == "host":
                ansible_user = MINIPC_USER
                ansible_ssh_pass = MINIPC_PASS
            else:
                ansible_user = SONIC_USER
                ansible_ssh_pass = SONIC_PASS

            # compose inventory line. We include ansible_ssh_pass and ansible_become_pass
            line = (
                f"{host_key} "
                f"ansible_host={ip} "
                f"ansible_user={ansible_user} "
                f"ansible_ssh_pass={ansible_ssh_pass} "
                f"ansible_python_interpreter=/usr/bin/python3 "
                f"ansible_become=yes "
                f"ansible_become_pass={ansible_ssh_pass} "
                f"asset_tag={asset} role={role} "
                f"res_iface={interface}\n"
            )

            fh.write(line)
            hosts_written.append(host_key)

    return inv_path, hosts_written
# function to convert window path into wsl compatible
def win_to_wsl_path(path):
    return "/mnt/" + path.replace("\\", "/").replace(":", "").lower()

def run_ansible_playbook(inventory_path: str, playbook_path: str, extra_vars: dict = None, timeout: int = 300):
    # function to run ansible-playbook
    if TEST:
        inv_path_wsl = win_to_wsl_path(inventory_path)  #convert paths if test mode, otherwise use normal path
        pb_path_wsl = win_to_wsl_path(playbook_path)

        cmd = ["wsl", "ansible-playbook", "-i", inv_path_wsl, pb_path_wsl]
    else:
        cmd = ["ansible-playbook", "-i", inventory_path, playbook_path]

    cmd += ["--forks", "15"]                                # useful for parallel operations

    if ANSIBLE_EXTRA_ARGS:
        cmd += ANSIBLE_EXTRA_ARGS.split()                   # add extra args if present
    if extra_vars:
        cmd += ["--extra-vars", json.dumps(extra_vars)]     # add extra vars if present
    print("Running:", " ".join(cmd))
    try:
        #proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout) #run playbook as subprocess
        #return proc.returncode, proc.stdout, proc.stderr
    #except subprocess.TimeoutExpired as te:
        #return 124, "", f"TimeoutExpired: {te}"
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            universal_newlines=True
        )

        stdout_lines = []
        stderr_lines = []

        # read real time result
        start_time = time.time()

        while True:
            if time.time() - start_time > timeout:
                proc.kill()
                return 124, ''.join(stdout_lines), f"TimeoutExpired after {timeout}s"

            # check if process is terminated
            if proc.poll() is not None:
                break

            # read stdout
            line = proc.stdout.readline()
            if line:
                print(line.rstrip())  # print in real time
                stdout_lines.append(line)

            time.sleep(0.1)  # small pause

        # read remaining lines
        remaining_out = proc.stdout.read()
        if remaining_out:
            print(remaining_out.rstrip())
            stdout_lines.append(remaining_out)

        remaining_err = proc.stderr.read()
        if remaining_err:
            stderr_lines.append(remaining_err)

        stdout = ''.join(stdout_lines)
        stderr = ''.join(stderr_lines)

        return proc.returncode, stdout, stderr

    except Exception as e:
        return 1, "", str(e)

def create_res_playbook_template(username, reservation_id, devices):
    # function to create template of playbooks that
    # add become properties to playbook
    template_with_become = re.sub(
        r'(^\s*- name:\s*Run commands from commands_map\s*\n)(\s*)(vars:)',
        lambda val: (
                val.group(1)
                + val.group(2)
                + "become: yes\n"
                + val.group(2)
                + f"become_user: {username}\n"
                + val.group(2)
                + "become_method: sudo\n"
                + val.group(2)
                + "vars:"
        ),
        INPUT_TEMPLATE_CONTENT,
        flags=re.MULTILINE
    )
    # ensure controllerPlaybooks dir exists (folder next to BASE_DIR)
    os.makedirs(CONTROLLER_PLAYBOOKS_DIR, exist_ok=True)

    # output filename: res_<reservation_id>_playbook_template.yml, this file will be inserted in controllerPlaybooks folder
    safe_out_name = safe_filename(f"res_{reservation_id}_playbook_template")
    out_filename = f"{safe_out_name}.yml"
    out_path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, out_filename)

    # build the commented entries to insert into the template as examples for user
    entries = []

    for d in devices:
        host  = d.get("id_device")
        ip = "192.168.15.10"
        if d.get("role") != "host":
            iface = "eth1"
        else:
            iface = "enp1s0"
        entries.append((host, ip, iface))
    indent = None
    # find line to insert commented lines for each device
    m = re.search(r'^(\s*)#\s*insert a list of commands after each device\s*$', template_with_become,
                  flags=re.MULTILINE)
    if m:
        indent = m.group(1)  # leading whitespace of the comment line

    else:
        # fallback: if placeholder not found, try to insert after 'commands_map:' line
        m = re.search(r'^(?P<indent>\s*)commands_map:\s*\n', template_with_become, flags=re.MULTILINE)
        if m:
            indent = m.group("indent") + "  "  # place entries under commands_map with extra indent

    entries_lines = []
    for (host, ip, iface) in entries:
        # same indent as comment 'insert a list of commands after each device' for first line
        entries_lines.append(f"{indent}#{host}:")
        # same indent + two spaces for the command comment
        entries_lines.append(f"{indent}  #- ip addr add {ip}/24 dev {iface}")
    generated_block = "\n".join(entries_lines) if entries_lines else f"{indent}# (no hosts found in inventory)"  # insert comment if no host is found

    # insert generated_block immediately after the placeholder comment line, but keep the placeholder comment in the file
    insert_pos = m.end()  # end of the matched comment line
    final_content = template_with_become[:insert_pos] + "\n" + generated_block + template_with_become[insert_pos:]

    # write file to controllerPlaybooks
    try:
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(final_content)
    except Exception as e:
        return jsonify({"ok": False, "message": f"Failed to write file: {e}"}), 500

@app.route('/api/controller/grantAccess', methods=['POST'])
def grant_access():
    # function to create reservation inventory and user account on each device
    print("Create ssh account for the user")
    data = request.get_json(silent=True)
    if not data:
        print("grantAccess: missing or invalid JSON")
        return jsonify({"ok": False, "message": "Missing or invalid JSON body"}), 400
    # get each filed from data received
    ssh_key = data.get("ssh_key")
    user_id = data.get("user_id")
    username = data.get("username")
    full_user =data.get("full_user")
    reservation_id = data.get("reservation_id")
    devices = data.get("devices")
    containerlab_test = data.get("containerlab_test")

    if ssh_key is None or user_id is None or username is None or reservation_id is None or devices is None or full_user is None:
        print("grantAccess: missing required fields")
        return jsonify({"ok": False, "message": "Missing required fields (ssh_key, user_id, username, devices)"}), 400

    print("GRANT ACCESS RECEIVED", data)

    # filter only devices with ip
    devices_with_ip = [d for d in devices if d.get("ip_device")]
    if not devices_with_ip:
        print("No devices with IP found in payload.")
        return jsonify({"ok": False, "message": "No devices with ip_device provided"}), 400

    # create inventory file (only devices with ip)
    inv_path, hosts = write_inventory(reservation_id, devices)
    print("Inventory written:", inv_path, "hosts:", hosts)

    if containerlab_test:
        active_reservations[username] = reservation_id
        return jsonify({"ok": True, "message": "Containerlab inventory created"}), 200

    # check grant playbook file
    pb_path = get_playbook_template_path("grant")
    if not pb_path:
        print("Grant playbook template not found in", INVENTORY_DIR, "- aborting")
        return jsonify({"ok": False, "message": "Grant playbook template missing on controller"}), 500
    print("Using playbook:", pb_path)

    # run ansible-playbook
    extra_vars = {"username": username, "ssh_key": ssh_key, "full_user": bool(full_user)}
    rc, out, err = run_ansible_playbook(inv_path, pb_path, extra_vars=extra_vars)
    #print("Ansible rc:", rc)
    #print("Ansible stdout:", out)
    #print("Ansible stderr:", err)

    if rc == 0:
        # user account creation completed
        if username and reservation_id is not None:
            create_res_playbook_template(username, reservation_id, devices)     # create template to download of reservation playbook
            # save reservation_id in active reservation list
            active_reservations[username] = reservation_id
            print(f"User {username} granted access and added to active_reservations")
            # create snapshot0
            safe_res = safe_filename(f"res_{reservation_id}_snapshots")
            res_dir = os.path.join(SNAPSHOTS_DIR, safe_res)
            name = "snapshot0"
            snap_dir = os.path.join(res_dir, safe_filename(name))

            # create snapshot directory
            os.makedirs(snap_dir, exist_ok=False)

            # write description file
            desc_path = os.path.join(snap_dir, "snapshot_description.txt")
            with open(desc_path, "w", encoding="utf-8") as fh:
                fh.write(str("Original network state, no configurations applied"))
            # run playbook to create snapshots
            playbook_path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, "get_snapshot_playbook.yml")
            extra_vars = {"name": name, "type": "snapshot", "reservation_id": reservation_id}

            print(f"Running playbook {playbook_path} for snapshot0 (reservation {reservation_id})")

            rc, out, err = run_ansible_playbook(inv_path, playbook_path, extra_vars=extra_vars)

            #print("Playbook rc:", rc)
            #print("Playbook stdout:", out)
            #print("Playbook stderr:", err)

            if rc == 0:
                return jsonify({"ok": True, "message": "Grant executed", "inventory": inv_path, "stdout": out, "stderr": err}), 200
            else:
                return jsonify({"ok": False, "message": "Ansible failed", "rc": rc, "stdout": out, "stderr": err}), 500
    else:
        return jsonify({"ok": False, "message": "Ansible failed", "rc": rc, "stdout": out, "stderr": err}), 500

def remove_files(file_path, file_type):
    # function to remove reservation files or folders after reservation
    if file_type == "file":
        try:
            if os.path.exists(file_path):
                os.remove(file_path)
                print(f"Deleted file: {file_path}")
            else:
                print(f"File not found (skipping): {file_path}")
        except Exception as e:
            print(f"Error deleting file {file_path}:", e)
    elif file_type == "folder":
        try:
            if os.path.exists(file_path):
                shutil.rmtree(file_path)
                print(f"Deleted folder: {file_path}")
            else:
                print(f"Folder not found (skipping): {file_path}")
        except Exception as e:
            print(f"Error deleting folder {file_path}:", e)

@app.route('/api/controller/revokeAccess', methods=['POST'])
def revoke_access():
    # function to revoke ssh access to user and remove reservation files
    print("Remove ssh account for the user")
    data = request.get_json(silent=True)
    if not data:
        print("revokeAccess: missing or invalid JSON")
        return jsonify({"ok": False, "message": "Missing or invalid JSON body"}), 400
    # get fields of received data
    ssh_key = data.get("ssh_key")
    username = data.get("username")
    reservation_id = data.get("reservation_id")
    run_rollback = data.get("rollback")

    if ssh_key is None or username is None or reservation_id is None or run_rollback is None:
        print("revokeAccess: missing required fields")
        return jsonify({"ok": False, "message": "Missing required fields (ssh_key, username, reservation_id, rollback)"}), 400

    print("REVOKE ACCESS RECEIVED", data)

    """
    if containerlab_test:
        del active_reservations[username]
        remove_files(f"res{reservation_id}", "file")
        print("Deleted generated files for reservation", reservation_id)
        return jsonify({"ok": True, "message": "Skip revoke operations for containerlab test"}), 200
    """

    # get inventory path
    safe_res = safe_filename(f"res-{reservation_id}-inventory")
    inv_path = os.path.join(INVENTORY_DIR, f"{safe_res}.ini")

    # get template path
    safe_res_template = safe_filename(f"res_{reservation_id}_playbook_template")
    playbook_template_path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, f"{safe_res_template}.yml")

    #  get controller running configs zip folder path
    safe_res_config = safe_filename(f"res_{reservation_id}_running_configs")
    controller_running_config_path = os.path.join( CONTROLLER_CONFIGS_DIR, f"{safe_res_config}.zip")

    # get res_<reservation_id> folder with user playbooks
    safe_res_dir = safe_filename(f"res_{reservation_id}")
    user_playbook_dir = os.path.join(USER_PLAYBOOKS_DIR, safe_res_dir)

    # get user running configs zip folder
    user_running_config_path = os.path.join(USER_CONFIGS_DIR, f"{safe_res_config}.zip")

    #  get controller running configs zip folder path
    safe_res_snapshots_dir = safe_filename(f"res_{reservation_id}_snapshots")
    res_snapshots_path = os.path.join(SNAPSHOTS_DIR, safe_res_snapshots_dir)

    out, err = None, None
    # skip revoke and rollback playbook if
    if run_rollback:
        # execute revoke playbook
        pb_path = get_playbook_template_path("revoke")
        if not pb_path:
            print("Revoke playbook template not found in", INVENTORY_DIR, "- aborting")
            return jsonify({"ok": False, "message": "Revoke playbook template missing on controller"}), 500
        print("Using revoke playbook:", pb_path)

        extra_vars = {"username": username, "ssh_key": ssh_key}
        rc, out, err = run_ansible_playbook(inv_path, pb_path, extra_vars=extra_vars)

        if rc != 0:
            return jsonify({"ok": False, "message": "Ansible revoke failed", "rc": rc, "stdout": out, "stderr": err}), 500

        print("Successful revoke playbook")

        pb_filename = "rollback_playbook.yml"
        pb_path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, pb_filename)
        # run rollback playbook with extra_vars required by client
        extra_vars = {"type": "rollback", "reservation_id": reservation_id, "name": "snapshot0"}
        print(f"Running rollback playbook {pb_path} for snapshot0 (reservation {reservation_id})")
        rc, out, err = run_ansible_playbook(inv_path, pb_path, extra_vars=extra_vars)

        if rc != 0:
            return jsonify({"ok": False, "message": f"Rollback playbook failed (rc={rc}, stdout={out}, stderr={err})"}), 500

        print("Successful rollback playbook")

    # delete inventory and playbook files
    # remove inventory file
    remove_files(inv_path, "file")

    # remove playbook template file
    remove_files(playbook_template_path, "file")

    # remove controller running config zip folder
    remove_files(controller_running_config_path, "file")

    # remove recursively the folder and all the content of user playbooks for the reservation
    remove_files(user_playbook_dir, "folder")

    # remove user running config zip folder
    remove_files(user_running_config_path, "file")

    # remove <res_id>_snapshots folder
    remove_files(res_snapshots_path, "folder")

    # remove active res file
    remove_files(f"res{reservation_id}", "file")
    print("Deleted generated files for reservation", reservation_id)

    if username in active_reservations:
        del active_reservations[username]  # remove reservation from active reservation list
        print(f"User {username} removed from active_reservations")

    if run_rollback:
        return jsonify({"ok": True, "message": "Revoke with rollback executed", "stdout": out, "stderr": err}), 200
    else:
        return jsonify({"ok": True, "message": "Cleaning without revoke executed"}), 200

@app.route('/api/controller/checkAvailability', methods=['GET'])
def check_availability():
    # check if the user has an active reservation, in this case the configuration can start, otherwise user must wait
    username = request.args.get("username")
    reservation_id = request.args.get("reservation_id")
    if not username or not reservation_id:
        return jsonify({"ok": False, "command": "error", "message": "Missing username or reservation_id parameter"}), 400
    print(f"Checking availability for user: {username}")

    if username in active_reservations or os.path.exists(f"res{reservation_id}"):
        # create file in case of controller restart, useful if the controller loses in memory active res information
        with open(f"res{reservation_id}", 'w') as file:
            file.write(f"{username}")

        print(f"User {username} found with reservation ID: {reservation_id}")
        return jsonify({"ok": True, "command": "start_configuration", "reservation_id": reservation_id}), 200
    else:
        print(f"User {username} not found in active reservations, reservation id: {reservation_id}")
        return jsonify({"ok": True, "command": "wait_configuration"}), 200


@app.route('/api/controller/cleanupReservation', methods=['POST'])
def cleanup_reservation():
    # remove reservation data from memory and filesystem, when admin remove the reservation
    data = request.get_json()
    reservation_id = data.get('reservation_id')
    username = data.get('username')

    if not reservation_id:
        return jsonify({"ok": False, "message": "Missing reservation_id parameter"}), 400

    print(f"Cleaning up reservation {reservation_id} for user {username}")

    # remove from active_reservations dictionary
    if username and username in active_reservations:
        if active_reservations[username] == reservation_id:
            del active_reservations[username]
            print(f"Removed {username} from active_reservations")

    # remove file if exists
    file_path = f"res{reservation_id}"
    if os.path.exists(file_path):
        try:
            os.remove(file_path)
            print(f"Removed file {file_path}")
        except Exception as e:
            print(f"Error removing file {file_path}: {e}")
            return jsonify({"ok": False, "message": f"Error removing file: {str(e)}"}), 500

    return jsonify({"ok": True, "message": "Reservation cleaned up successfully"}), 200

@app.route('/api/controller/getSnapshots', methods=['GET'])
def get_snapshots():
    # function to create current snapshot of the network
    reservation_id = request.args.get("reservation_id")
    if not reservation_id:
        return jsonify({"ok": False, "message": "Missing reservation_id parameter"}), 400

    # sanitize reservation_id for filesystem use
    safe_res = safe_filename(f"res_{reservation_id}_snapshots")
    res_dir = os.path.join(SNAPSHOTS_DIR, safe_res)

    if not os.path.exists(res_dir) or not os.path.isdir(res_dir):
        # if no snapshots folder exists, return empty list
        return jsonify({"ok": False, "message": "No present snapshots"}), 500

    try:
        entries = os.listdir(res_dir)       # list of snapshot directories inside current reservation snapshot dir
    except Exception as e:
        print("Error listing snapshots directory:", e)
        return jsonify({"ok": False, "message": f"Failed to list snapshots: {e}"}), 500

    # filter only directories named snapshotN
    snap_dirs = []
    for name in entries:
        full = os.path.join(res_dir, name)      # create entire path (res_<reservation_id>_snapshots/snapshot<N>)
        if os.path.isdir(full) and name.startswith("snapshot"):
            # try to extract numeric index for sorting, fallback to 0
            m = re.match(r"snapshot(\d+)$", name)
            idx = int(m.group(1)) if m else 0
            snap_dirs.append((idx, name))

    # sort by numeric index ascending
    snap_dirs.sort(key=lambda x: x[0])

    snapshots = []
    for _, snap_name in snap_dirs:
        snap_path = os.path.join(res_dir, snap_name)
        desc_file = os.path.join(snap_path, "snapshot_description.txt")
        description = ""
        try:
            if os.path.exists(desc_file) and os.path.isfile(desc_file):
                with open(desc_file, "r", encoding="utf-8") as fh:
                    description = fh.read().strip()                 # read description file for each snapshot<N> folder inside current snapshot reservation folder
        except Exception as e:
            print(f"Warning: could not read description for {snap_name}: {e}")
            description = ""
        # create list of <name>, <description> couples
        snapshots.append({"name": snap_name, "description": description})

    return jsonify({"ok": True, "snapshots": snapshots}), 200

@app.route('/api/controller/deleteSnapshot', methods=['DELETE', 'POST'])
def delete_snapshot():
    # delete snapshot, accept either query params (for DELETE) or JSON body (for POST)
    data = request.get_json(silent=True) or {}
    reservation_id = request.args.get("reservation_id") or data.get("reservation_id")
    name = request.args.get("name") or data.get("name")

    if not reservation_id or not name:
        return jsonify({"ok": False, "message": "Missing reservation_id or snapshot name"}), 400

    # snapshot names expected like "snapshot1", "snapshot2", ... also prevent accidental removal of base snapshot0
    if not re.match(r"^snapshot\d+$", name) or name == "snapshot0":
        return jsonify({"ok": False, "message": f"Cannot delete {name}"}), 400

    # build safe paths for snapshots
    safe_res = safe_filename(f"res_{reservation_id}_snapshots")
    res_dir = os.path.join(SNAPSHOTS_DIR, safe_res)
    snap_path = os.path.join(res_dir, safe_filename(name))

    if not os.path.exists(res_dir) or not os.path.isdir(res_dir):
        return jsonify({"ok": False, "message": "Snapshots directory for reservation not found"}), 404

    if not os.path.exists(snap_path) or not os.path.isdir(snap_path):
        return jsonify({"ok": False, "message": f"Snapshot '{name}' not found"}), 404

    try:
        # remove directory and its content
        shutil.rmtree(snap_path)
        print(f"Deleted snapshot folder: {snap_path}")
        return jsonify({"ok": True, "message": f"Snapshot '{name}' deleted"}), 200
    except Exception as e:
        print(f"Error deleting snapshot {snap_path}: {e}")
        return jsonify({"ok": False, "message": f"Failed to delete snapshot: {e}"}), 500

@app.route('/api/controller/createSnapshot', methods=['POST'])
def create_snapshot():
    # create new snapshot
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"ok": False, "message": "Missing or invalid JSON body"}), 400

    reservation_id = data.get("reservation_id")
    name = data.get("name")
    description = data.get("description", "")

    if not reservation_id or not name or not description:
        return jsonify({"ok": False, "message": "Missing reservation_id or name or description"}), 400

    # basic validation for snapshot name (expects snapshotN)
    if not re.match(r"^snapshot\d+$", name):
        return jsonify({"ok": False, "message": "Invalid snapshot name (expected 'snapshot<N>')"}), 400

    # build safe paths for snapshot reservation folder and snapshot folders
    safe_res = safe_filename(f"res_{reservation_id}_snapshots")
    res_dir = os.path.join(SNAPSHOTS_DIR, safe_res)
    snap_dir = os.path.join(res_dir, safe_filename(name))

    try:
        # ensure base snapshots dir exists
        os.makedirs(res_dir, exist_ok=True)

        # prevent overwriting an existing snapshot
        if os.path.exists(snap_dir):
            return jsonify({"ok": False, "message": f"Snapshot '{name}' already exists"}), 409

        # create snapshot directory
        os.makedirs(snap_dir, exist_ok=False)

        # write description file
        desc_path = os.path.join(snap_dir, "snapshot_description.txt")
        with open(desc_path, "w", encoding="utf-8") as fh:
            fh.write(str(description or ""))

        print(f"Created snapshot {snap_dir} with description")
        # create inventory path
        safe_res_inv = safe_filename(f"res-{reservation_id}-inventory")
        inv_path = os.path.join(INVENTORY_DIR, f"{safe_res_inv}.ini")
        if not os.path.exists(inv_path):
            print("Inventory for reservation not found (will still attempt playbook):", inv_path)
        # run playbook for snapshot creation
        playbook_path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, "get_snapshot_playbook.yml")
        extra_vars = {"name": name, "type": "snapshot", "reservation_id": reservation_id}

        print(f"Running playbook {playbook_path} for snapshot {name} (reservation {reservation_id})")

        rc, out, err = run_ansible_playbook(inv_path, playbook_path, extra_vars=extra_vars)

        #print("Playbook rc:", rc)
        #print("Playbook stdout:", out)
        #print("Playbook stderr:", err)

        if rc == 0:
            return jsonify({"ok": True, "message": f"Snapshot '{name}' created", "name": name}), 200
        else:
            # snapshot created but playbook failed
            return jsonify({"ok": False, "message": f"Error during snapshot '{name}' creation, playbook failed"}), 400

    except Exception as e:
        print(f"Error creating snapshot {snap_dir}: {e}")
        # cleanup on failure if directory was partially created
        if os.path.exists(snap_dir):
            shutil.rmtree(snap_dir)

        return jsonify({"ok": False, "message": f"Failed to create snapshot: {e}"}), 500

@app.route('/api/controller/rollback', methods=['POST'])
def rollback():
    # function to apply configuration rollback
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"ok": False, "message": "Missing or invalid JSON body"}), 400

    reservation_id = data.get("reservation_id")
    name = data.get("name")

    if not reservation_id or not name:
        return jsonify({"ok": False, "message": "Missing reservation_id or name"}), 400

    # validate snapshot name (expects snapshotN)
    if not re.match(r"^snapshot\d+$", name):
        return jsonify({"ok": False, "message": "Invalid snapshot name"}), 400

    # build safe paths and check snapshot exists
    safe_res = safe_filename(f"res_{reservation_id}_snapshots")
    res_dir = os.path.join(SNAPSHOTS_DIR, safe_res)
    snap_path = os.path.join(res_dir, safe_filename(name))

    if not os.path.exists(res_dir):
        return jsonify({"ok": False, "message": "Snapshots directory for reservation not found"}), 404

    if not os.path.exists(snap_path):
        return jsonify({"ok": False, "message": f"Snapshot '{name}' not found"}), 404

    # find rollback playbook in controller playbooks dir
    pb_filename = "rollback_playbook.yml"
    pb_path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, pb_filename)
    if not os.path.exists(pb_path):
        msg = f"Rollback playbook '{pb_filename}' not found in {CONTROLLER_PLAYBOOKS_DIR}"
        print(msg)
        return jsonify({"ok": False, "message": msg}), 500

    # build inventory path
    safe_res_inv = safe_filename(f"res-{reservation_id}-inventory")
    inv_path = os.path.join(INVENTORY_DIR, f"{safe_res_inv}.ini")

    # run rollback playbook with extra_vars required by client
    extra_vars = {"type": "rollback", "reservation_id": reservation_id, "name": name}
    print(f"Running rollback playbook {pb_path} for snapshot {name} (reservation {reservation_id})")
    rc, out, err = run_ansible_playbook(inv_path, pb_path, extra_vars=extra_vars)

    #print("Rollback playbook rc:", rc)
    #print("Rollback playbook stdout:", out)
    #print("Rollback playbook stderr:", err)

    if rc == 0:
        return jsonify({"ok": True, "message": f"Rollback to '{name}' completed"}), 200
    else:
        return jsonify({"ok": False, "message": f"Rollback playbook failed (rc={rc})"}), 500

if __name__ == '__main__':

    # host 0.0.0.0 often necessary in virtual environments or containers.
    app.run(debug=True, host='0.0.0.0', port=5002, use_reloader=False)