import os
import json
import re
import subprocess
from flask import jsonify, request
from ..app import app

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INVENTORY_DIR = os.path.join(BASE_DIR, "inventories")
CONTROLLER_PLAYBOOKS_DIR = os.path.join(BASE_DIR, "controllerPlaybooks")
TEMPLATES_DIR = os.path.join(CONTROLLER_PLAYBOOKS_DIR, "templates")
WRAPPERS_DIR = os.path.join(CONTROLLER_PLAYBOOKS_DIR, "wrappers")

ANSIBLE_EXTRA_ARGS = ""            #  extra args (ex. -c paramiko)
# default credentials per role
SONIC_USER = "admin"
SONIC_PASS = "YourPaSsWoRd"
MINIPC_USER = "oem"
MINIPC_PASS = "oem123"
active_reservations = {}    # dictionary that contains active and usable (after key insertion) reservation
TEST = True                 # if true uses wsl on windows (/mnt), otherwise normal paths

def safe_filename(name: str) -> str:
    # sanitize a string for use as filename
    s = str(name or "")
    s = re.sub(r"[^\w\-.]", "_", s)
    return s

def ensure_inventory_dir():
    os.makedirs(INVENTORY_DIR, exist_ok=True)
    return INVENTORY_DIR

def get_playbook_template_path(kind: str):
    """
    Return the path of playbook template for 'grant' or 'revoke' in the folder INVENTORY_DIR, None otherwise.
      - grant  -> <CONTROLLER_PLAYBOOKS_DIR>/grant_playbook.yml
      - revoke -> <CONTROLLER_PLAYBOOKS_DIR>/revoke_playbook.yml
    """
    kind = (kind or "").lower()
    if kind == "grant":
        filename = "grant_playbook.yml"
    elif kind == "revoke":
        filename = "revoke_playbook.yml"
    else:
        return None

    path = os.path.join(CONTROLLER_PLAYBOOKS_DIR, filename)
    return path if os.path.exists(path) else None

def write_inventory(reservation_id: int, devices: list):
    """
    Create INI inventory file with hosts that have ip_device not None.
    devices: list of dict {"id_device", "ip_device", "role"}
    Returns path to inventory file and list of hostnames written.
    """
    inv_dir = ensure_inventory_dir()
    safe_res = safe_filename(f"res-{reservation_id}-inventory")
    inv_path = os.path.join(inv_dir, f"{safe_res}.ini")

    hosts_written = []

    with open(inv_path, "w", encoding="utf-8") as fh:
        fh.write("# Inventory generated by controller\n")
        fh.write("[all]\n")
        for d in devices:
            asset = d.get("id_device")
            role = (d.get("role") or "").lower()
            ip = d.get("ip_device")
            interface = d.get("interface")
            if not ip:
                print("Skipping device without IP:", asset)
                continue
            # if asset tag missing, take the ip and change . with _ to create a valid string
            host_key = safe_filename(asset) if asset else ip.replace(".", "_")

            # pick credentials depending on role
            if role == "host":
                ansible_user = MINIPC_USER
                ansible_ssh_pass = MINIPC_PASS
            else:
                ansible_user = SONIC_USER
                ansible_ssh_pass = SONIC_PASS

            # Compose inventory line. We include ansible_ssh_pass and ansible_become_pass
            line = (
                f"{host_key} "
                f"ansible_host={ip} "
                f"ansible_user={ansible_user} "
                f"ansible_ssh_pass={ansible_ssh_pass} "
                f"ansible_python_interpreter=/usr/bin/python3 "
                f"ansible_become=yes "
                f"ansible_become_pass={ansible_ssh_pass} "
                f"asset_tag={asset} role={role} "
                f"res_iface={interface}\n"
            )

            fh.write(line)
            hosts_written.append(host_key)

    return inv_path, hosts_written

def win_to_wsl_path(path):
    return "/mnt/" + path.replace("\\", "/").replace(":", "").lower()

def run_ansible_playbook(inventory_path: str, playbook_path: str, extra_vars: dict = None, timeout: int = 300):
    # runs ansible-playbook
    if TEST:
        inv_path_wsl = win_to_wsl_path(inventory_path)
        pb_path_wsl = win_to_wsl_path(playbook_path)

        cmd = ["wsl", "ansible-playbook", "-i", inv_path_wsl, pb_path_wsl]
    else:
        cmd = ["ansible-playbook", "-i", inventory_path, playbook_path]

    if ANSIBLE_EXTRA_ARGS:
        cmd += ANSIBLE_EXTRA_ARGS.split()
    if extra_vars:
        cmd += ["--extra-vars", json.dumps(extra_vars)]
    print("Running:", " ".join(cmd))
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return proc.returncode, proc.stdout, proc.stderr
    except subprocess.TimeoutExpired as te:
        return 124, "", f"TimeoutExpired: {te}"
    except Exception as e:
        return 1, "", str(e)


@app.route('/api/controller/grantAccess', methods=['POST'])
def grant_access():
    print("Create ssh account for the user")
    data = request.get_json(silent=True)
    if not data:
        print("grantAccess: missing or invalid JSON")
        return jsonify({"ok": False, "message": "Missing or invalid JSON body"}), 400

    ssh_key = data.get("ssh_key")
    user_id = data.get("user_id")
    username = data.get("username")
    full_user =data.get("full_user")
    reservation_id = data.get("reservation_id")
    devices = data.get("devices")


    if ssh_key is None or user_id is None or username is None or reservation_id is None or devices is None or full_user is None:
        print("grantAccess: missing required fields")
        return jsonify({"ok": False, "message": "Missing required fields (ssh_key, user_id, username, devices)"}), 400

    print("GRANT ACCESS RECEIVED", data)

    # filter only devices with ip
    devices_with_ip = [d for d in devices if d.get("ip_device")]
    if not devices_with_ip:
        print("No devices with IP found in payload.")
        return jsonify({"ok": False, "message": "No devices with ip_device provided"}), 400

    # create inventory file (only devices with ip)
    inv_path, hosts = write_inventory(reservation_id, devices)
    print("Inventory written:", inv_path, "hosts:", hosts)

    # write playbook file
    pb_path = get_playbook_template_path("grant")
    if not pb_path:
        print("Grant playbook template not found in", INVENTORY_DIR, "- aborting")
        return jsonify({"ok": False, "message": "Grant playbook template missing on controller"}), 500
    print("Using playbook:", pb_path)

    # run ansible-playbook
    extra_vars = {"username": username, "ssh_key": ssh_key, "full_user": bool(full_user)}
    rc, out, err = run_ansible_playbook(inv_path, pb_path, extra_vars=extra_vars)
    print("Ansible rc:", rc)
    print("Ansible stdout:", out)
    print("Ansible stderr:", err)

    if rc == 0:
        # user account creation completed
        if username and reservation_id is not None:
            active_reservations[username] = reservation_id
            print(f"User {username} granted access and added to active_reservations")
        return jsonify({"ok": True, "message": "Grant executed", "inventory": inv_path, "stdout": out, "stderr": err}), 200
    else:
        return jsonify({"ok": False, "message": "Ansible failed", "rc": rc, "stdout": out, "stderr": err}), 500

@app.route('/api/controller/revokeAccess', methods=['POST'])
def revoke_access():
    print("Remove ssh account for the user")
    data = request.get_json(silent=True)
    if not data:
        print("revokeAccess: missing or invalid JSON")
        return jsonify({"ok": False, "message": "Missing or invalid JSON body"}), 400

    ssh_key = data.get("ssh_key")
    user_id = data.get("user_id")
    username = data.get("username")
    reservation_id = data.get("reservation_id")

    if ssh_key is None or user_id is None or username is None or reservation_id is None:
        print("revokeAccess: missing required fields")
        return jsonify({"ok": False, "message": "Missing required fields (ssh_key, user_id, username, reservation_id)"}), 400

    print("REVOKE ACCESS RECEIVED", data)

    # inventory path
    safe_res = safe_filename(f"res-{reservation_id}-inventory")
    inv_path = os.path.join(INVENTORY_DIR, f"{safe_res}.ini")
    if not os.path.exists(inv_path):
       print("Inventory not found:", inv_path, " still attempting graceful removal (playbook will run against nothing).")

    # write revoke playbook
    pb_path = get_playbook_template_path("revoke")
    if not pb_path:
        print("Revoke playbook template not found in", INVENTORY_DIR, "- aborting")
        return jsonify({"ok": False, "message": "Revoke playbook template missing on controller"}), 500
    print("Using revoke playbook:", pb_path)

    extra_vars = {"username": username, "ssh_key": ssh_key}
    rc, out, err = run_ansible_playbook(inv_path, pb_path, extra_vars=extra_vars)
    print("Ansible revoke rc:", rc)
    print("Ansible revoke stdout:", out)
    print("Ansible revoke stderr:", err)

    # delete inventory and playbook files
    try:
        # remove inventory file
        if os.path.exists(inv_path):
            os.remove(inv_path)

        print("Deleted generated inventory file for reservation", reservation_id)
    except Exception as e:
        print("Error deleting inventory file:", e)

    if rc == 0:
        # revoked user account
        if username in active_reservations:
            del active_reservations[username]
            print(f"User {username} removed from active_reservations")
        return jsonify({"ok": True, "message": "Revoke executed", "stdout": out, "stderr": err}), 200
    else:
        return jsonify({"ok": False, "message": "Ansible revoke failed", "rc": rc, "stdout": out, "stderr": err}), 500


@app.route('/api/controller/checkAvailability', methods=['GET'])
def check_availability():
    # check if the user has an active reservation, in this case the configuration can start, otherwise wait
    username = request.args.get("username")

    if not username:
        return jsonify({"ok": False, "command": "error", "message": "Missing username parameter"}), 400

    print(f"Checking availability for user: {username}")

    if username in active_reservations:
        reservation_id = active_reservations[username]
        print(f"User {username} found with reservation ID: {reservation_id}")
        return jsonify({"ok": True, "command": "start_configuration", "reservation_id": reservation_id}), 200
    else:
        print(f"User {username} not found in active reservations.")
        return jsonify({"ok": True, "command": "wait_configuration"}), 200

if __name__ == '__main__':

    # host 0.0.0.0 often necessary in virtual environments or containers.
    app.run(debug=True, host='0.0.0.0', port=5002)