- name: Fetch SONiC config_db.json from non-host devices
  hosts: all
  gather_facts: no
  vars:
    controller_dest_dir: "controllerConfigs"
    reservation_id: " "
  pre_tasks:
    - name: Ensure controller destination dir exists
      delegate_to: localhost
      run_once: true
      ansible.builtin.file:
        path: "{{ controller_dest_dir }}"
        state: directory
        mode: '0755'

  tasks:
    - name: Fetch sonic config_db.json from devices that are not role 'host'
      ansible.builtin.fetch:
        src: /etc/sonic/config_db.json
        dest: "{{ controller_dest_dir }}/res_{{reservation_id}}_running_configs/{{ inventory_hostname }}_config_db.json"
        flat: yes
      when: hostvars[inventory_hostname].get('role', '') != 'host'
      ignore_errors: yes
