import json
import os
import time
import uuid
import traceback
from ...app import app
from .prompts import AGENT_PROMPTS, DIAGNOSTIC_ASSISTANT_PROMPTS, INTERACTIVE_ASSISTANT_PROMPTS
from .safety_logic import execute_safety_phase
from ...config import MAX_DIAGNOSTIC_ASSISTANT_MESSAGES, PHASES_ORDER, DIAGNOSTIC_ASSISTANT_PHASES_ORDER, INTERACTIVE_ASSISTANT_PHASES_ORDER
from .agent_server_utils import (redis_client, get_last_agent_message, format_as_string, parse_plan, 
                                open_ssh_connections, run_parallel_commands, close_ssh_connections, get_validated_llm_reply, is_command_whitelisted,
                                run_agent_execution_plan, delete_agent_history_keys, consume_llm_stream_with_retries, get_dynamic_device_rules, 
                                get_reserved_devices, get_testbed_topology, extract_xml_tag)

# helper function to handle the chat logic for execution experiment phases, manages context history to send to the agents and system prompts
def handle_experiment_chat_logic(username, reservation_id, chat_id, agent_role, message, llm_model, files=None):
    
    # ---------------------------------------------- CONTEXT AND HISTORY MANAGEMENT ----------------------------------------------
    # if there is no chat_id, it means the user is starting a new chat. We generate one.
    if not chat_id:
        chat_id = f"{int(time.time())}_{uuid.uuid4().hex[:8]}"          # added timestamp to guarantee chronological order of messages

    # get redis session key
    session_key = f"agent_history:{agent_role}:{username}:{reservation_id}:{chat_id}"

    # retrieve history from Redis
    history_str = redis_client.get(session_key)

    # load history from redis, otherwise create the fisrt system message with system prompt
    if history_str:
        history = json.loads(history_str)
    else:
        # create first message that includes the system prompt, dynamic rules for device kinds if present, the topology and reserved devices
        testbed_topology = get_testbed_topology(reservation_id)
    
        system_prompt = AGENT_PROMPTS.get(agent_role)

        dynamic_rules = get_dynamic_device_rules(agent_role, reservation_id)
        if dynamic_rules:
            system_prompt += f"\n<device_specific_rules>\n{dynamic_rules}\n</device_specific_rules>\n"

        system_prompt += f"\n\n<topology>\n```yaml\n{testbed_topology}\n```\n</topology>\n"

        # add reserved devices in he system prompt
        system_prompt += get_reserved_devices(reservation_id)

        # initialize history if it doesn't exist
        history = [{"role": "system", "content": system_prompt}]

    # add user message and file info to conversation history
    user_content = message
    if files:
       for f in files:
            if f.filename != '':
                try:
                    # read the content of the file and append it to the user message in a structured way
                    file_content = f.read().decode('utf-8')
                    user_content += f"\n\n<attached_file name=\"{f.filename}\">\n{file_content}\n</attached_file>\n"
                    
                except UnicodeDecodeError:
                    # message if the file is not a text file or cannot be decoded
                    user_content += f"\n\n<attached_file name=\"{f.filename}\">\n[Note: The file was ignored because it is not a readable text file.]\n</attached_file>\n"

    # extract system prompt (index 0) from the history and last user message, the message that the user has written or the message automatically generated by the system in the previous phase
    system_msg = history[0] 
    latest_user_msg = {"role": "user", "content": user_content} if user_content.strip() else None

    # append user message to the history if it exists
    if latest_user_msg: 
        history.append(latest_user_msg)

    # for planning and execution we use a minimal array. Negotiation use all the history.
    if agent_role in ["planning", "execution"]:
        
        llm_history = [system_msg]
        if latest_user_msg:
            llm_history.append(latest_user_msg)
    else:
        llm_history = history

    # ---------------------------------------------- LLM CALL ----------------------------------------------
    # send request to the LLM
    valid_output, reply = yield from consume_llm_stream_with_retries(llm_history, agent_role, llm_model, reservation_id)
    
    if not valid_output:
        print(f"[DEBUG SERVER] FINAL FAILURE DETAILS (safety): {reply}")
        raise Exception("LLM failed to produce valid JSON after retries")

    # ---------------------------------------------- POST EXECUTION OPERATION AND REDIS STORAGE ----------------------------------------------
    # add "MODE: DIRECT COMMAND EXECUTION" string to the context for the current configuration loop, if execution mode is DIRECT_COMMANDS
    if agent_role == "negotiation" and "APPROVED" in str(reply.get("status", "")).upper():
        if str(reply.get("execution_mode", "")).upper() == "DIRECT_COMMANDS":
            original_context = reply.get("context_for_planning", "")
            reply["context_for_planning"] = "MODE: DIRECT COMMAND EXECUTION\n\n" + str(original_context)
    
    # append the agent reply to the history
    history.append({"role": "assistant", "content": json.dumps(reply)})

    current_time = time.time()
    for msg in history:
        # assign timestamp to a message
        if "timestamp" not in msg:
            msg["timestamp"] = current_time
            # add a millisecond to guarantee that messages created in the same time are sequentially ordered
            current_time += 0.001       

    # save updated history to Redis (expiration set to 5 days as security, when the reservation ends, the key is automatically removed)
    redis_client.set(session_key, json.dumps(history), ex=432000)
    
    return reply, chat_id

# helper function to handle the chat logic for diagnostic assistant phases, manages context history to send to the agents and system prompts    
def handle_diagnostic_chat_logic(username, reservation_id, chat_id, agent_role, message, llm_model, files=None):

    # ---------------------------------------------- CONTEXT AND HISTORY MANAGEMENT ----------------------------------------------
    # if there is no chat_id, it means the user is starting a new chat. We generate one.
    if not chat_id:
        chat_id = f"{int(time.time())}_{uuid.uuid4().hex[:8]}"          # added timestamp to guarantee chronological order of messages

    # get session key from Redis
    session_key = f"agent_history:diagnostic_assistant_chat:{username}:{reservation_id}:{chat_id}"

    # retrieve history from Redis
    history_str = redis_client.get(session_key)

    # load history from Redis if exists, otherwise create the first system message with system prompt
    if history_str:
        history = json.loads(history_str)
    else:
        # create first message that includes the system prompt, dynamic rules for device kinds if present and the topology
        testbed_topology = get_testbed_topology(reservation_id)
        
        system_prompt = DIAGNOSTIC_ASSISTANT_PROMPTS["diagnostic_intent"]
       
        dynamic_rules = get_dynamic_device_rules("diagnostic_intent", reservation_id)
        if dynamic_rules:
            system_prompt += f"\n<device_specific_rules>\n{dynamic_rules}\n</device_specific_rules>\n"

        system_prompt += f"\n\n<topology>\n```yaml\n{testbed_topology}\n```\n</topology>\n"

        # add reserved devices constraint list to the system prompt
        system_prompt += get_reserved_devices(reservation_id)

        # initialize history if it doesn't exist
        history = [{"role": "system", "content": system_prompt}]

    # add user message and file info to conversation history
    user_content = message
    if files and agent_role == "diagnostic_intent":
       for f in files:
            if f.filename != '':
                try:
                    # read the content of the file and append it to the user message in a structured way
                    file_content = f.read().decode('utf-8')
                    user_content += f"\n\n<attached_file name=\"{f.filename}\">\n{file_content}\n</attached_file>\n"
                    
                except UnicodeDecodeError:
                    # message if the file is not a text file or cannot be decoded
                    user_content += f"\n\n<attached_file name=\"{f.filename}\">\n[Note: The file was ignored because it is not a readable text file.]\n</attached_file>\n"

     # initialize last user message, the message written by the user or automatically generated by the system in the previous phase
    latest_user_msg = {"role": "user", "content": user_content} if user_content.strip() else None
    
    if agent_role == "diagnostic_intent":
        # find the index of the last generated summary
        last_summary_idx = -1
        for i in range(len(history) - 1, -1, -1):
            if history[i].get("role") == "summary":
                last_summary_idx = i
                break

        # get the first message after last summary
        start_idx = last_summary_idx + 1 if last_summary_idx != -1 else 1
        # get the number of user messages since last summary, add the latest user message if present
        user_msg_count = sum(1 for m in history[start_idx:] if m.get("role") == "user") + (1 if latest_user_msg else 0)

        # if the limit is surpassed, generate a new summary by clling the summarizer agent
        if user_msg_count >= MAX_DIAGNOSTIC_ASSISTANT_MESSAGES:
            summarizer_sys_prompt = DIAGNOSTIC_ASSISTANT_PROMPTS["diagnostic_summarizer"]
            summarizer_history = [{"role": "system", "content": summarizer_sys_prompt}]

            # send to summarizer the last generated summary if exists
            if last_summary_idx != -1:
                summarizer_history.append({"role": "system", "content": f"<previous_chat_summary>\n{history[last_summary_idx]['content']}\n</previous_chat_summary>"})

            # add every message after the last summary, except execution_log type messages (messages with the output of reading commands)
            for m in history[start_idx:]:
                if m.get("role") != "execution_log":
                    summarizer_history.append(m)

            # add a temporary message to instruct summarizer to create the summary (the agent return with stop error if the last message is a system message)
            summarizer_history.append({"role": "user", "content": "Please generate the JSON summary of the conversation above based exactly on your system instructions."})

            # send request to the summarizer
            is_valid_sum, _, summary_json = get_validated_llm_reply(summarizer_history, "diagnostic_summarizer", llm_model, reservation_id)

            if is_valid_sum:
                # append summary content in the history, if the output is valid
                history.append({"role": "summary", "content": summary_json.get("summary", "")})
                print("[DEBUG] Chat limit reached. New summary appended to global history.")

                # update indexes
                last_summary_idx = len(history) - 1
                
        # append user message
        if latest_user_msg: 
            history.append(latest_user_msg)

        # create active window to send to the intent agent, send the summary as temporary system message, in redis is saved as summary message to retrieve easily the last summary
        active_window = [history[0]]
        if last_summary_idx != -1:
            # append the last summary to the system prompt
            active_window.append({"role": "system", "content": f"<previous_chat_summary>\n{history[last_summary_idx]['content']}\n</previous_chat_summary>"})
        start_idx = last_summary_idx + 1 if last_summary_idx != -1 else 1

        # add messages from the last summary to the end of the history
        active_window.extend(history[start_idx:])

        # filter execution_log messages
        llm_history = [m for m in active_window if m.get("role") != "execution_log"]
    
    elif agent_role == "diagnostic_planner":
            # create system prompt for the agent and create local history
            testbed_topology = get_testbed_topology(reservation_id)
            sys_prompt = DIAGNOSTIC_ASSISTANT_PROMPTS.get(agent_role)
            dynamic_rules = get_dynamic_device_rules(agent_role, reservation_id)
            
            if dynamic_rules: sys_prompt += f"\n<device_specific_rules>\n{dynamic_rules}\n</device_specific_rules>\n"
            sys_prompt += f"\n\n<topology>\n```yaml\n{testbed_topology}\n```\n</topology>\n"
            sys_prompt += get_reserved_devices(reservation_id)
            
            llm_history = [{"role": "system", "content": sys_prompt}]   
            if latest_user_msg:
                llm_history.append(latest_user_msg)

    elif agent_role == "diagnostic_reporter":
        # create system prompt for the agent and create local history
        testbed_topology = get_testbed_topology(reservation_id)
        sys_prompt = DIAGNOSTIC_ASSISTANT_PROMPTS.get(agent_role)
        dynamic_rules = get_dynamic_device_rules(agent_role, reservation_id)
            
        if dynamic_rules:
            sys_prompt += f"\n<device_specific_rules>\n{dynamic_rules}\n</device_specific_rules>\n"
        sys_prompt += f"\n\n<topology>\n```yaml\n{testbed_topology}\n```\n</topology>\n"
            
        llm_history = [{"role": "system", "content": sys_prompt}]
        if latest_user_msg:
            llm_history.append(latest_user_msg)
                
    # ---------------------------------------------- LLM CALL ----------------------------------------------
    # send request to the LLM
    valid_output, reply = yield from consume_llm_stream_with_retries(llm_history, agent_role, llm_model, reservation_id)
    
    if not valid_output:
        print(f"[DEBUG SERVER] FINAL FAILURE DETAILS (safety): {reply}")
        raise Exception("LLM failed to produce valid JSON after retries")

    # ---------------------------------------------- POST EXECUTION OPERATION AND REDIS STORAGE ----------------------------------------------
    if agent_role == "diagnostic_intent":
        status = str(reply.get("status", "")).upper()
        if status in ["REJECTED", "PROMPT_GENERATED"]:
            # append teh response to the history if the status is REJECTED or PROMPT_GENERATED, if APPROVED we move to the next phase, there is no necessity to save that state in the history
            history.append({"role": "assistant", "content": reply.get("response", "")})

    elif agent_role == "diagnostic_reporter":
        exec_report = extract_xml_tag(user_content, "execution_report") if user_content else ""
        # append the execution log and the reporter response to the history 
        history.append({"role": "execution_log", "content": exec_report})
        history.append({"role": "assistant", "content": reply.get("response", "")})

    # planner messages are not saved in redis    
    if agent_role != "diagnostic_planner":
        current_time = time.time()
        for msg in history:
            # assign timestamp to a message
            if "timestamp" not in msg:
                msg["timestamp"] = current_time
                # add a millisecond to guarantee that messages created in the same time are sequentially ordered
                current_time += 0.001       

        # save updated history to Redis (expiration set to 5 days as security, when the reservation ends, the key is automatically removed)
        redis_client.set(session_key, json.dumps(history), ex=432000)
    
    return reply, chat_id

def handle_interactive_chat_logic(username, reservation_id, chat_id, message, llm_model):
    if not chat_id:
        chat_id = f"{int(time.time())}_{uuid.uuid4().hex[:8]}"

    session_key = f"agent_history:interactive_assistant_chat:{username}:{reservation_id}:{chat_id}"
    history_str = redis_client.get(session_key)

    if history_str:
        history = json.loads(history_str)
    else:
        testbed_topology = get_testbed_topology(reservation_id)
        system_prompt = INTERACTIVE_ASSISTANT_PROMPTS["interactive_negotiator"]
        dynamic_rules = get_dynamic_device_rules("interactive_negotiator", reservation_id)
        
        if dynamic_rules:
            system_prompt += f"\n<device_specific_rules>\n{dynamic_rules}\n</device_specific_rules>\n"
        system_prompt += f"\n\n<topology>\n```yaml\n{testbed_topology}\n```\n</topology>\n"
        system_prompt += get_reserved_devices(reservation_id)

        history = [{"role": "system", "content": system_prompt}]

    if message.strip():
        history.append({"role": "user", "content": message.strip()})

    valid_output, reply = yield from consume_llm_stream_with_retries(history, "interactive_negotiator", llm_model, reservation_id)
    
    if not valid_output:
        raise Exception("LLM failed to produce valid JSON after retries")

    history.append({"role": "assistant", "content": json.dumps(reply)})

    current_time = time.time()
    for msg in history:
        if "timestamp" not in msg:
            msg["timestamp"] = current_time
            current_time += 0.001       

    redis_client.set(session_key, json.dumps(history), ex=432000)
    
    return reply, chat_id, history

# generate the SSE stream for the execution phases, handle the logic and the conditions to determine next phase for every agent     
def generate_experiment_phase_sse(request_data, files):
    username = request_data.get('username', '')
    reservation_id = request_data.get('reservation_id', '')
    chat_id = request_data.get('chat_id', '')
    current_phase = request_data.get('current_phase', '')
    message = request_data.get('message', '')
    llm_model = request_data.get('llm_model')
    execution_mode = request_data.get('execution_mode', 'serial')
    is_manual_chat = request_data.get('is_manual_chat', False)
    context_payload = request_data.get('context', '')

    experiment_context = "No specific experiment context provided."
    exit_conditions = "No specific exit conditions provided."

    # fetch history context if the current phase is not negotiation
    if current_phase != "negotiation" and chat_id:
        # get the last negotiation message
        is_valid_negotiation, parsed_negotiation = get_last_agent_message(username, reservation_id, chat_id, "negotiation")
        # retrieve experiment context and exit conditions from the last APPROVED negotiation message
        if is_valid_negotiation and parsed_negotiation.get("status") == "APPROVED":
            experiment_context = format_as_string(parsed_negotiation.get("context_for_planning", ""))
            exit_conditions = format_as_string(parsed_negotiation.get("exit_conditions", ""))

    # retrieve dynamically the next phase from configuration array
    next_phase = None
    if current_phase in PHASES_ORDER:
        idx = PHASES_ORDER.index(current_phase)
        if idx + 1 < len(PHASES_ORDER):
            next_phase = PHASES_ORDER[idx + 1]

    try:
        if current_phase == "negotiation":
            # send request to the LLM
            final_reply, chat_id_out = yield from handle_experiment_chat_logic(username, reservation_id, chat_id, current_phase, message, llm_model, files)
            # retrieve status and final reply from the answer
            status = str(final_reply.get("status", "")).upper()
            result_data = {"chat_id": chat_id_out, "reply": json.dumps(final_reply)}

            if "APPROVED" in status:
                # retrieve the context and exit conditions to send to the next phase
                raw_context = format_as_string(final_reply.get("context_for_planning", ""))
                raw_exit = format_as_string(final_reply.get("exit_conditions", ""))
                next_context = f"<experiment_context>\n{raw_context}\n</experiment_context>\n\n<exit_conditions>\n{raw_exit}\n</exit_conditions>"
                # update result_data with the context and next phase to send to the worker function
                result_data.update({"context": next_context, "next_phase": next_phase})
            else:
                # if the message is not approved, we send clarifiyng questions and the next phase remains negotiation
                result_data.update({"requires_answers": True, "questions": final_reply.get("clarifying_questions", []), "next_phase": current_phase})

            # send data to the worker function
            yield f"data: {json.dumps({'type': 'result', 'data': result_data})}\n\n"

        elif current_phase == "planning":
            execution_report = "No report found."
            old_plan = "No previous plan found."

            # the user has requested to retry from the planning phase after failed execution
            if message.strip() == "RETRY_PLANNING":
                # delete safety temporary context for the previous turn of safety
                delete_agent_history_keys(username=username, reservation_id=reservation_id, chat_id=chat_id, role_prefix="safety_turn_state")
                
                # get the report generated by the execution agent
                is_parsed_execution_valid, parsed_execution = get_last_agent_message(username, reservation_id, chat_id, "execution")

                if is_parsed_execution_valid:
                    execution_report = format_as_string(parsed_execution.get("report", ""))

                # retrieve the approved experiment plan from the safety agent
                is_parsed_safety_valid, parsed_safety = get_last_agent_message(username, reservation_id, chat_id, "safety")

                if is_parsed_safety_valid:
                    old_plan = format_as_string(parsed_safety.get("executable_plan", ""))
                
                # generate the message to send to the planning
                message = f"Please analyze the errors below and generate a NEW corrected execution plan. You MUST respond in a valid JSON object.\n\n<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<failed_execution_plan>\n{old_plan}\n</failed_execution_plan>\n\n<execution_report>\n{execution_report}\n</execution_report>"

            # add user message to the context returned by the client if  we are not in a retry in planning phase    
            elif context_payload:
                message = context_payload + ("\n\n" + message if message.strip() else "")

            # send request to the LLM
            final_reply, chat_id_out = yield from handle_experiment_chat_logic(username, reservation_id, chat_id, current_phase, message, llm_model, files)

            status = str(final_reply.get("status", "")).upper()
            result_data = {"chat_id": chat_id_out}

            # create context and update next phase, if the plan is approved, otherwise remain in the current phase
            if "APPROVED" in status:
                plan = format_as_string(final_reply.get("execution_plan", ""))
                verification = format_as_string(final_reply.get("verification", []))
                next_context = f"<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<execution_plan>\n{plan}\n</execution_plan>\n\n<verification_commands>\n{verification}\n</verification_commands>\n\n<device_report>\nnull\n</device_report>"
                result_data.update({"context": next_context, "next_phase": next_phase})
            else:
                result_data.update({"next_phase": current_phase})

            # send result to the worker function
            yield f"data: {json.dumps({'type': 'result', 'data': result_data})}\n\n"

        elif current_phase == "safety":
            # retrieve last user message if present in this phase
            if context_payload:
                message = context_payload + ("\n\n" + message if message.strip() else "")

            latest_user_msg = {"role": "user", "content": message} if message.strip() else None
        
            # run the safety loop (requests to the LLM are excuted in this function)
            final_reply = yield from execute_safety_phase(username, chat_id, latest_user_msg, reservation_id, llm_model, is_manual_chat)
            chat_id_out = chat_id

            status = str(final_reply.get("status", "")).upper()

            # show only some fields of safety message
            filtered_reply = {"status": status, "executable_plan": final_reply.get("executable_plan", []), "verification_plan": final_reply.get("verification_plan", [])}
            # add issues field only if the plan was rejected
            if "REJECTED" in status: filtered_reply["issues"] = final_reply.get("issues", [])
            # add clarifying questions if present
            if final_reply.get("clarifying_questions"): filtered_reply["clarifying_questions"] = final_reply.get("clarifying_questions")

            # update result_data with filterd reply
            result_data = {"chat_id": chat_id_out, "reply": json.dumps(filtered_reply)}

            # create context and update next phase, if the plan is approved, otherwise remain in the current phase
            if "APPROVED" in status:
                # extract plan and verification commands from safety final response
                safe_exec_plan = format_as_string(final_reply.get("executable_plan", []))
                safe_verif_plan = format_as_string(final_reply.get("verification_plan", []))
                # send the extracted fields to the testbed execution phase
                safe_context = f"<approved_exec_plan>\n{safe_exec_plan}\n</approved_exec_plan>\n\n<approved_verif_plan>\n{safe_verif_plan}\n</approved_verif_plan>"    
                result_data.update({"context": safe_context, "next_phase": next_phase})
            else:
                result_data.update({"is_safety_stopped": True, "next_phase": current_phase})

            # send result to the worker function
            yield f"data: {json.dumps({'type': 'result', 'data': result_data})}\n\n"

        elif current_phase == "testbed_execution":
            # send message to show in the frontend before starting execution of the plan on devices
            yield f"data: {json.dumps({'type': 'thought', 'content': f'\n\n[System: Executing verified plan on testbed...]\n\n'})}\n\n"

            # retrieve the approved experiment plan and verification commands from the safety agent
            plan_str = extract_xml_tag(context_payload, "approved_exec_plan")
            v_plan_str = extract_xml_tag(context_payload, "approved_verif_plan")
            
            plan = [line.strip() for line in plan_str.split('\n') if line.strip()]
            v_plan = [line.strip() for line in v_plan_str.split('\n') if line.strip()]

            # get the path of ansible inventory
            base_dir = os.path.dirname(os.path.abspath(__file__))
            inventory_path = os.path.abspath(os.path.join(base_dir, "..", "..", "controller", "inventories", f"res-{reservation_id}-inventory.ini"))

            plan = parse_plan(plan)
            v_plan = parse_plan(v_plan)

            # if there are commands to execute for plan and verification, we execute commands on devices
            if len(plan) > 0 and len(v_plan) > 0:

                if execution_mode == "parallel":
                    # in parallel execution mode, commands are executed in parallel for differente devices, execution and verification are maintained separated and serial for consistency
                    all_devices = set()
                    for item in plan + v_plan:
                        if ":" in item:
                            # get all involved devices from the plans
                            all_devices.add(item.split(":", 1)[0].strip())

                    # create connections to all devices in the plan and verification
                    shared_connections = open_ssh_connections(all_devices, inventory_path, reservation_id)

                    start_time = time.time()
                    
                    # execute the plans and close the connextion after the execution
                    try:
                        exec_report = run_parallel_commands(inventory_path, plan, reservation_id, is_intent=False, connections=shared_connections)
                        verif_report = run_parallel_commands(inventory_path, v_plan, reservation_id, is_intent=False, connections=shared_connections)
                    finally:
                        close_ssh_connections(shared_connections)

                    # generate execution report
                    execution_report = f"--- CONFIGURATION REPORT ---\n{exec_report}\n\n--- VERIFICATION REPORT ---\n{verif_report}"

                    elapsed_time = time.time() - start_time
                    print(f"\n[DEBUG EXECUTION] --- PARALLEL PLAN EXECUTED IN {elapsed_time:.2f} SECONDS ---")  

                else:
                    # in serial mode, every command is executed following the order of the execution and verification plans
                    complete_plan = plan + v_plan

                    start_time = time.time()

                    execution_report = run_agent_execution_plan(inventory_path, complete_plan, reservation_id)

                    elapsed_time = time.time() - start_time
                    print(f"\n[DEBUG EXECUTION] --- SERIAL PLAN EXECUTED IN {elapsed_time:.2f} SECONDS ---") 

                # create context for the next phase    
                next_context = f"<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<execution_results>\n{execution_report}\n</execution_results>\n"
            else:
                next_context = f"<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<execution_results>\nNo execution plan was provided. Report that the safety check passed with no commands to execute.\n</execution_results>\n"

            # update result_data with new context and next phase    
            result_data = {"chat_id": chat_id, "context": next_context, "next_phase": next_phase}

            # send result data to the worker function
            yield f"data: {json.dumps({'type': 'result', 'data': result_data})}\n\n"

        elif current_phase == "execution":
            # get message from context if present
            if context_payload:
                message = context_payload + ("\n\n" + message if message.strip() else "")

            # send request to the LLM
            final_reply, chat_id_out = yield from handle_experiment_chat_logic(username, reservation_id, chat_id, current_phase, message, llm_model, files)

            # update result_data
            status = str(final_reply.get("status", "")).upper()
            result_data = {"chat_id": chat_id_out, "reply": json.dumps(final_reply)}

            # there is no next phase if teh experiment is approved, if is rejeted, the next phase is planning
            if "APPROVED" in status:
                result_data.update({"next_phase": None})
            else:
                plan_phase = PHASES_ORDER[PHASES_ORDER.index("planning")]
                result_data.update({"execution_rejected": True, "next_phase": plan_phase})

            # send result data to the worker function
            yield f"data: {json.dumps({'type': 'result', 'data': result_data})}\n\n"
            
    except Exception as e:
        yield f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n"
            
# manage troubleshooter flow with streaming of reasoning, handle the logic and the conditions to determine next phase for every agent   
def generate_diagnostic_assistant_sse(request_data):
    print("[DEBUG SSE] Start SSE generator...")

    username = request_data['username']
    reservation_id = request_data['reservation_id']
    chat_id = request_data['chat_id']
    message = request_data['message']
    llm_model = request_data['llm_model']
    current_phase = request_data['current_phase']
    context = request_data['context']
    execution_report = request_data['execution_report']
    safe_commands = request_data['safe_commands']
    approved_commands = request_data['approved_commands']   

    # compute dynamically the next phase
    next_phase = None
    if current_phase in DIAGNOSTIC_ASSISTANT_PHASES_ORDER:
        idx = DIAGNOSTIC_ASSISTANT_PHASES_ORDER.index(current_phase)
        if idx + 1 < len(DIAGNOSTIC_ASSISTANT_PHASES_ORDER):
            next_phase = DIAGNOSTIC_ASSISTANT_PHASES_ORDER[idx + 1]

    try:
        if current_phase == "diagnostic_intent":
            # send request to the LLM
            final_reply, chat_id_out = yield from handle_diagnostic_chat_logic(username, reservation_id, chat_id, current_phase, message, llm_model)

            status = final_reply.get("status", "").upper()
            response_msg = final_reply.get("response", "")
            next_context = final_reply.get("context", "")
            print(f"[DEBUG SSE] Intent Status: {status}")

            # determine the next phase and send updated response to the worker
            if status in ["REJECTED", "PROMPT_GENERATED"]:
                yield f"data: {json.dumps({'type': 'result', 'data': {'reply': response_msg, 'chat_id': chat_id_out, 'requires_approval': False, 'next_phase': None}})}\n\n"
            else:
                yield f"data: {json.dumps({'type': 'result', 'data': {'chat_id': chat_id_out, 'requires_approval': False, 'context': next_context, 'next_phase': next_phase}})}\n\n"

        elif current_phase == "diagnostic_planner":
            # create context and send request to the LLM
            planner_msg = f"<context>\n{context}\n</context>"
            final_reply, chat_id_out = yield from handle_diagnostic_chat_logic(username, reservation_id, chat_id, current_phase, planner_msg, llm_model)

            diag_cmds = final_reply.get("diagnostic_commands", [])
            approve_cmds = final_reply.get("commands_to_approve", [])
            safe_cmds = []
            pending_cmds = approve_cmds.copy()
            
            print(f"[DEBUG SSE] Planner ended. Safe commands: {len(diag_cmds)}, Commands to approve: {len(approve_cmds)}")

            # check if the commands are whitelisted, if so, add them to a list, otherwise add them to the pending commands list to ask user for approval
            for cmd_str in diag_cmds:
                if ":" in cmd_str:
                    dev, cmd = cmd_str.split(":", 1)
                    if is_command_whitelisted(cmd): safe_cmds.append(cmd_str)
                    else: pending_cmds.append(cmd_str)

            # determine next phase and send updated data to the worker
            if pending_cmds:
                # ask approval to the frontend
                # return context and chat_id so that the fontend resend this data
                yield f"data: {json.dumps({'type': 'result', 'data': {'chat_id': chat_id_out, 'requires_approval': True, 'commands': pending_cmds, 'safe_commands': safe_cmds, 'context': context, 'next_phase': next_phase}})}\n\n"
            else:
                yield f"data: {json.dumps({'type': 'result', 'data': {'chat_id': chat_id_out, 'requires_approval': False, 'safe_commands': safe_cmds, 'context': context, 'next_phase': next_phase}})}\n\n"

        elif current_phase == "execution":
            # unify safe (inside whitelist) and user approved commands
            raw_commands_to_run = safe_commands + approved_commands
            commands_to_run = []

            # add count or timeout to possible infinite read commands, read only last 50 raws of log files
            for cmd_str in raw_commands_to_run:
                if ":" in cmd_str:
                    dev, cmd = cmd_str.split(":", 1)
                    cmd = cmd.strip()
                    if cmd.startswith("ping ") and "-c" not in cmd:
                        cmd = cmd.replace("ping ", "ping -c 4 ", 1)
                    elif (cmd.startswith("iperf ") or cmd.startswith("iperf3 ")) and "-t" not in cmd:
                        cmd = cmd.replace("iperf", "iperf -t 10", 1)
                    elif "tcpdump" in cmd and "timeout" not in cmd:
                        cmd = f"timeout 10 {cmd}"
                    elif cmd.startswith("cat /var/log/"):
                        cmd = cmd.replace("cat ", "tail -n 50 ", 1)
                    commands_to_run.append(f"{dev}: {cmd}")
                else:
                    commands_to_run.append(cmd_str)
            
            # create execution report with a message if there are not commands to run, otherwise with the output of the commands executed on devices
            if not commands_to_run:
                exec_report = "[SYSTEM LOG]: The user rejected all proposed commands. No read operations were performed. Inform the user that you cannot complete the analysis without executing the commands, and ask them to try again or rephrase their request."
            else:
                base_dir = os.path.dirname(os.path.abspath(__file__))
                inventory_path = os.path.abspath(os.path.join(base_dir, "..", "..", "controller", "inventories", f"res-{reservation_id}-inventory.ini"))
                
                exec_report = run_parallel_commands(inventory_path, commands_to_run, reservation_id, is_intent=False)

            # send execution report to the worker and update next phase
            yield f"data: {json.dumps({'type': 'result', 'data': {'chat_id': chat_id, 'requires_approval': False, 'execution_report': exec_report, 'context': context, 'next_phase': next_phase}})}\n\n"

        elif current_phase == "diagnostic_reporter":
            # create the context for the reporter agent and send request to the LLM
            reporter_msg = f"<context>\n{context}\n</context>\n<execution_report>\n{execution_report}\n</execution_report>"
            final_reply, chat_id_out = yield from handle_diagnostic_chat_logic(username, reservation_id, chat_id, current_phase, reporter_msg, llm_model)

            final_response = final_reply.get("response", "Error during report generation")

            # send result to the worker and set None for the next phase since the pipeline is concluded
            yield f"data: {json.dumps({'type': 'result', 'data': {'reply': final_response, 'chat_id': chat_id_out, 'requires_approval': False, 'execution_log': execution_report, 'next_phase': None}})}\n\n"

    except Exception as e:
        print(f"\n[DEBUG SSE] Exception in SSE generator: {str(e)}")
        traceback.print_exc()
        yield f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n"
    
    print("[DEBUG SSE] SSE generator ended \n" + "="*50)

def generate_interactive_assistant_sse(request_data):
    username = request_data['username']
    reservation_id = request_data['reservation_id']
    chat_id = request_data['chat_id']
    message = request_data['message']
    llm_model = request_data['llm_model']
    current_phase = request_data['current_phase']
    
    next_phase = None
    if current_phase in INTERACTIVE_ASSISTANT_PHASES_ORDER:
        idx = INTERACTIVE_ASSISTANT_PHASES_ORDER.index(current_phase)
        if idx + 1 < len(INTERACTIVE_ASSISTANT_PHASES_ORDER):
            next_phase = INTERACTIVE_ASSISTANT_PHASES_ORDER[idx + 1]

    try:
        if current_phase == "interactive_negotiator":
            final_reply, chat_id_out, history = yield from handle_interactive_chat_logic(username, reservation_id, chat_id, message, llm_model)
            
            status = final_reply.get("status", "").upper()
            proposed_cmds = final_reply.get("proposed_commands", [])

            if status == "APPROVED" and proposed_cmds:
                # Passa all'esecuzione
                request_data['proposed_commands'] = proposed_cmds
                yield f"data: {json.dumps({'type': 'result', 'data': {'chat_id': chat_id_out, 'next_phase': next_phase}})}\n\n"
            else:
                # Resta in attesa di approvazione o chiarimenti (mostra i comandi proposti nella UI se ci sono)
                yield f"data: {json.dumps({'type': 'result', 'data': {'reply': json.dumps(final_reply), 'chat_id': chat_id_out, 'next_phase': None}})}\n\n"

        elif current_phase == "execution":
            cmds_to_run = request_data.get('proposed_commands', [])
            
            if cmds_to_run:
                base_dir = os.path.dirname(os.path.abspath(__file__))
                inventory_path = os.path.abspath(os.path.join(base_dir, "..", "..", "controller", "inventories", f"res-{reservation_id}-inventory.ini"))
                exec_report = run_parallel_commands(inventory_path, cmds_to_run, reservation_id, is_intent=False)
            else:
                exec_report = "No commands provided to execute."

            # Salva il report nella history globale per farlo leggere all'agente al turno successivo
            session_key = f"agent_history:interactive_assistant_chat:{username}:{reservation_id}:{chat_id}"
            history_str = redis_client.get(session_key)
            if history_str:
                history = json.loads(history_str)
                history.append({"role": "execution_log", "content": f"<execution_report>\n{exec_report}\n</execution_report>"})
                redis_client.set(session_key, json.dumps(history), ex=432000)

            yield f"data: {json.dumps({'type': 'result', 'data': {'chat_id': chat_id, 'execution_report': exec_report, 'next_phase': None}})}\n\n"

    except Exception as e:
        yield f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n"

# background worker fo experiment that runs the while loop. Evaluates agents sequentially, publishes SSE strings to Redis, and evaluates loop termination
def run_experiment_pipeline_worker(request_data, files):
    # get chat_id
    chat_id = request_data.get('chat_id')
    channel = f"channel:chat_{chat_id}"

    # we must run inside app_context to allow database access
    with app.app_context():
        try:
            # loop of the experiemnt pipeline
            while True:
                # manage experiment pipeline
                generator = generate_experiment_phase_sse(request_data, files)
                phase_transitioned = False
                should_stop = False

                for chunk in generator:
                    # publish every SSE reasoning chunk on redis
                    redis_client.publish(channel, chunk)

                    if chunk.startswith("data: "):
                        try:
                            # get data payload and retrieve every parameter
                            data_payload = json.loads(chunk[6:])
                            if data_payload.get("type") == "result":
                                res_data = data_payload.get("data", {})
                                next_phase = res_data.get("next_phase")
                                requires_answers = res_data.get("requires_answers")
                                execution_rejected = res_data.get("execution_rejected")
                                is_safety_stopped = res_data.get("is_safety_stopped")

                                # check if we need pause to let user decide to continue the loop (if the execution produced rejected results), pause for human (if there are questions), or end experiment (there is not a next phase, there are not questions and execution plan is not rejected)
                                if not next_phase or is_safety_stopped or requires_answers or execution_rejected:
                                    should_stop = True
                                    break # human intervention or end
                    
                                # setup for next iteration
                                request_data["current_phase"] = next_phase
                                if "context" in res_data:
                                    request_data["context"] = res_data["context"]
                                
                                request_data["message"] = ""
                                files = [] # files are only sent on the very first phase
                                phase_transitioned = True
                                break
                        except json.JSONDecodeError:
                            pass        
                # end loop                
                if should_stop or not phase_transitioned:
                    break
                
        except Exception as e:
            redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n")
        finally:
            # tell the HTTP route that the stream is finished
            redis_client.publish(channel, "EOF")

# background worker for diagnostic that runs the while loop. Evaluates agents sequentially, publishes SSE strings to Redis, and evaluates loop termination
def run_diagnostic_pipeline_worker(request_data):
    # get chat_id
    chat_id = request_data['chat_id']
    channel = f"channel:chat_{chat_id}"
    
    with app.app_context():
        try:
            while True:
                # we iterate the generator function to extract its yields and publish them to Redis, the function manages the logic of the assistant
                generator = generate_diagnostic_assistant_sse(request_data=request_data)
                phase_transitioned = False
                should_stop = False
            
                for chunk in generator:
                    # the generator yields strings formatted like "data: {...}\n\n"
                    redis_client.publish(channel, chunk)
                
                    # check if the generated chunk is a "result" that requires approval or ends the phase
                    if chunk.startswith("data: "):
                        try:
                            # retrieve parameters
                            data_payload = json.loads(chunk[6:])
                            if data_payload.get("type") == "result":
                                res_data = data_payload.get("data", {})
                                next_phase = res_data.get("next_phase")
                                requires_approval = res_data.get("requires_approval")
                            
                                # if we hit an approval or there is no next phase, stop the worker
                                if requires_approval or not next_phase:
                                    should_stop = True
                                    break
                                
                                # otherwise, prepare the payload for the next phase and loop internally
                                request_data['current_phase'] = next_phase
                                if "context" in res_data: request_data['context'] = res_data['context']
                                if "safe_commands" in res_data: request_data['safe_commands'] = res_data['safe_commands']
                                if "execution_report" in res_data: request_data['execution_report'] = res_data['execution_report']
                            
                                phase_transitioned = True
                                break

                        except json.JSONDecodeError:
                            pass
                # interrupt the loop if the phase is not changed or stop is necessary
                if should_stop or not phase_transitioned:
                    break

        except Exception as e:
            redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n")
        finally:
            # advertise HTTP route to close connection
            redis_client.publish(channel, "EOF")


def run_interactive_pipeline_worker(request_data):
    chat_id = request_data['chat_id']
    channel = f"channel:chat_{chat_id}"
    
    with app.app_context():
        try:
            while True:
                generator = generate_interactive_assistant_sse(request_data)
                phase_transitioned = False
                should_stop = False
            
                for chunk in generator:
                    redis_client.publish(channel, chunk)
                    if chunk.startswith("data: "):
                        try:
                            data_payload = json.loads(chunk[6:])
                            if data_payload.get("type") == "result":
                                res_data = data_payload.get("data", {})
                                next_phase = res_data.get("next_phase")
                            
                                if not next_phase:
                                    should_stop = True
                                    break
                                
                                request_data['current_phase'] = next_phase
                                phase_transitioned = True
                                break
                        except json.JSONDecodeError:
                            pass
                if should_stop or not phase_transitioned:
                    break
        except Exception as e:
            redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n")
        finally:
            redis_client.publish(channel, "EOF")