import json
import os
import time
from ...app import app
from .agent_server_utils import (redis_client, get_last_agent_message, format_as_string, handle_chat_logic,
                                 parse_plan, open_ssh_connections, run_parallel_commands,
                                 close_ssh_connections, run_agent_execution_plan, generate_diagnostic_assistant_sse)

def run_experiment_pipeline_worker(username, reservation_id, chat_id, starting_phase, initial_message, llm_model, execution_mode, files, is_manual_chat, context_payload):
    # background worker that runs the while loop. Evaluates agents sequentially and publishes SSE strings to Redis
    channel = f"channel:chat_{chat_id}"
    current_phase = starting_phase
    message = initial_message
    
    # we must run inside app_context to allow database access
    with app.app_context():
        try:
            # retrieve negotiation experiment context if available, it is common for next agents, usefull also in execution when the experiment is not approved
            experiment_context = "No specific experiment context provided."
            exit_conditions = "No specific exit conditions provided."
            execution_report = "No report found."
            old_plan = "No previous plan found."

            # loop of the experiemnt pipeline
            while current_phase:
                
                # fetch history context if skipping negotiation
                if current_phase in ["planning", "safety", "execution"] and chat_id:

                    is_valid_negotiation, parsed_negotiation = get_last_agent_message(username, reservation_id, chat_id, "negotiation")

                    if is_valid_negotiation and parsed_negotiation.get("status") == "APPROVED":
                        experiment_context = format_as_string(parsed_negotiation.get("context_for_planning", ""))
                        exit_conditions = format_as_string(parsed_negotiation.get("exit_conditions", ""))

                if current_phase == "planning" and message.strip() == "RETRY_PLANNING":
                    # get the report generated by the execution agent
                    is_parsed_execution_valid, parsed_execution = get_last_agent_message(username, reservation_id, chat_id, "execution")

                    if is_parsed_execution_valid:
                        execution_report = format_as_string(parsed_execution.get("report", ""))

                    # retrieve the approved experiment plan from the safety agent
                    is_parsed_safety_valid, parsed_safety = get_last_agent_message(username, reservation_id, chat_id, "safety")

                    if is_parsed_safety_valid:
                        old_plan = format_as_string(parsed_safety.get("executable_plan", ""))

                    message = f"Please analyze the errors below and generate a NEW corrected execution plan. You MUST respond in a valid JSON object.\n\n<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<failed_execution_plan>\n{old_plan}\n</failed_execution_plan>\n\n<execution_report>\n{execution_report}\n</execution_report>"

                # add user message to the context resturned by the client if the current phase is not negotiation and we are not in a retry in planning phase    
                elif current_phase != "negotiation" and context_payload:
                    message = context_payload + ("\n\n" + message if message.strip() else "")

                # run LLM logic sending reasoning in streaming for current phase
                generator = handle_chat_logic(username, reservation_id, chat_id, current_phase, message, llm_model, files, is_manual_chat)
                final_reply = None
                chat_id_out = chat_id
                
                try:
                    while True:
                        # get reasoning tokens (already formatted as SSE string) and publish in the channel
                        chunk = next(generator)
                        redis_client.publish(channel, chunk)
                except StopIteration as e:
                    # when handle_chat_logic ends, an exception is raised and the final value of the function can be retrieved
                    final_reply, chat_id_out = e.value
                except Exception as e:
                    redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n")
                    break
                
                if not final_reply:
                    redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': 'No reply generated'}})}\n\n")
                    break

                # get final reply of the agent after reasoning
                parsed = final_reply
                status = str(parsed.get("status", "")).upper()

                filtered_reply = None
                
                if current_phase == "negotiation" or current_phase == "execution":
                    # show complete negotiation message
                    filtered_reply = parsed

                # for planning, filtered_reply is None (we never show the planning message)    
                elif current_phase == "safety":
                    # show only some fields of safety message
                    filtered_reply = {"status": status, "executable_plan": parsed.get("executable_plan", []), "verification_plan": parsed.get("verification_plan", [])}
                    # add issues field only if the plan was rejected
                    if "REJECTED" in status: filtered_reply["issues"] = parsed.get("issues", [])
                    # add clarifying questions if present
                    if parsed.get("clarifying_questions"): filtered_reply["clarifying_questions"] = parsed.get("clarifying_questions")

                # update result_data only if there is reply that can be shown
                result_data = {"chat_id": chat_id_out}
                if filtered_reply:
                    result_data["reply"] = json.dumps(filtered_reply)

                # for every phase add to result_data the context for the next agent and the name of the next agent
                if current_phase == "negotiation":
                    if "APPROVED" in status:
                        raw_context = format_as_string(parsed.get("context_for_planning", ""))
                        raw_exit = format_as_string(parsed.get("exit_conditions", ""))
                        next_context = f"<experiment_context>\n{raw_context}\n</experiment_context>\n\n<exit_conditions>\n{raw_exit}\n</exit_conditions>"
                        result_data.update({"context": next_context, "next_phase": "planning"})
                    else:
                        result_data.update({"requires_answers": True, "questions": parsed.get("clarifying_questions", []), "next_phase": "negotiation"})

                elif current_phase == "planning":
                    if "APPROVED" in status:
                        plan = format_as_string(parsed.get("execution_plan", ""))
                        verification = format_as_string(parsed.get("verification", []))
                        next_context = f"<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<execution_plan>\n{plan}\n</execution_plan>\n\n<verification_commands>\n{verification}\n</verification_commands>\n\n<device_report>\nnull\n</device_report>"
                        result_data.update({"context": next_context, "next_phase": "safety"})

                elif current_phase == "safety":
                    if "APPROVED" in status:
                        
                        # execute physical SSH commands
                        plan = parsed.get("executable_plan", "[]")
                        v_plan = parsed.get("verification_plan", [])

                        base_dir = os.path.dirname(os.path.abspath(__file__))
                        inventory_path = os.path.abspath(os.path.join(base_dir, "..", "..", "controller", "inventories", f"res-{reservation_id}-inventory.ini"))

                        plan = parse_plan(plan)
                        v_plan = parse_plan(v_plan)

                        # add message to show before starting execution of the plan on devices
                        if len(plan) > 0 and len(v_plan) > 0:
                            # publish the message to show the experiemtn execution
                            redis_client.publish(channel, f"data: {json.dumps({'type': 'thought', 'content': f'\n\n[System: Executing verified plan on testbed...]\n\n'})}\n\n")

                            if execution_mode == "parallel":
                                # in parallel execution mode, commands are executed in parallel for differente devices, execution and verification are maintained separated and serial for consistency
                                all_devices = set()
                                for item in plan + v_plan:
                                    if ":" in item:
                                        all_devices.add(item.split(":", 1)[0].strip())

                                shared_connections = open_ssh_connections(all_devices, inventory_path, reservation_id)

                                start_time = time.time()
                                
                                try:
                                    exec_report = run_parallel_commands(inventory_path, plan, reservation_id, is_intent=False, connections=shared_connections)
                                    verif_report = run_parallel_commands(inventory_path, v_plan, reservation_id, is_intent=False, connections=shared_connections)
                                finally:
                                    close_ssh_connections(shared_connections)

                                execution_report = f"--- CONFIGURATION REPORT ---\n{exec_report}\n\n--- VERIFICATION REPORT ---\n{verif_report}"

                                elapsed_time = time.time() - start_time
                                print(f"\n[DEBUG EXECUTION] --- PARALLEL PLAN EXECUTED IN {elapsed_time:.2f} SECONDS ---")  

                            else:
                                # in serial mode, every command is executed following the rder of the execution and verification plans
                                complete_plan = plan + v_plan

                                start_time = time.time()

                                execution_report = run_agent_execution_plan(inventory_path, complete_plan, reservation_id)

                                elapsed_time = time.time() - start_time
                                print(f"\n[DEBUG EXECUTION] --- SERIAL PLAN EXECUTED IN {elapsed_time:.2f} SECONDS ---") 
                                
                            next_context = f"<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<execution_results>\n{execution_report}\n</execution_results>\n"
                        else:
                            next_context = f"<experiment_context>\n{experiment_context}\n</experiment_context>\n\n<exit_conditions>\n{exit_conditions}\n</exit_conditions>\n\n<execution_results>\nNo execution plan was provided. Report that the safety check passed with no commands to execute.\n</execution_results>\n"
                            
                        result_data.update({"context": next_context, "next_phase": "execution"})

                    else:
                        result_data.update({"next_phase": "safety"})

                elif current_phase == "execution":
                    if "APPROVED" in status:
                        result_data.update({"next_phase": None})
                    else:
                        result_data.update({"execution_rejected": True, "next_phase": "planning"})

                # publish final result for the current phase
                redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': result_data})}\n\n")

                # get next phase from current phase data
                next_phase = result_data.get("next_phase")

                # check for stop conditions in in safety
                is_safety_stopped = (current_phase == "safety" and "APPROVED" not in status)

                # check if we need pause to let user decide to continue the loop (if the execution produced rejected results), pause for human (if there are questions), or end experiment (there is not a next phase, there are not questions and execution plan is not rejected)
                if not next_phase or result_data.get("requires_answers") or result_data.get("execution_rejected") or is_safety_stopped:
                    break # human intervention or end
                    
                # setup for next iteration
                current_phase = next_phase
                message = ""
                context_payload = result_data.get("context", "")
                files = [] # files are only sent on the very first phase

        except Exception as e:
            redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n")
        finally:
            # tell the HTTP route that the stream is finished
            redis_client.publish(channel, "EOF")

def run_diagnostic_pipeline_worker(request_data, history):
    chat_id = request_data['chat_id']
    channel = f"channel:chat_{chat_id}"
    
    with app.app_context():
        try:
            while True:
                # we iterate the generator function to extract its yields and publish them to Redis
                generator = generate_diagnostic_assistant_sse(history=history, request_data=request_data)
                phase_transitioned = False
                should_stop = False
            
                for chunk in generator:
                    # the generator yields strings formatted like "data: {...}\n\n"
                    redis_client.publish(channel, chunk)
                
                    # check if the generated chunk is a "result" that requires approval or ends the phase
                    if chunk.startswith("data: "):
                        try:
                            data_payload = json.loads(chunk[6:])
                            if data_payload.get("type") == "result":
                                res_data = data_payload.get("data", {})
                                next_phase = res_data.get("next_phase")
                                requires_approval = res_data.get("requires_approval")
                            
                                # if we hit an approval or there is no next phase, stop the worker
                                if requires_approval or not next_phase:
                                    should_stop = True
                                    break
                                
                                # otherwise, prepare the payload for the next phase and loop internally
                                request_data['current_phase'] = next_phase
                                if "context" in res_data: request_data['context'] = res_data['context']
                                if "safe_commands" in res_data: request_data['safe_commands'] = res_data['safe_commands']
                                if "execution_report" in res_data: request_data['execution_report'] = res_data['execution_report']
                            
                                phase_transitioned = True
                                break

                        except json.JSONDecodeError:
                            pass
                # interrupt the loop if the phase is not changed or stop is necessary
                if should_stop or not phase_transitioned:
                    break

        except Exception as e:
            redis_client.publish(channel, f"data: {json.dumps({'type': 'result', 'data': {'error': str(e)}})}\n\n")
        finally:
            # advertise HTTP route to close connection
            redis_client.publish(channel, "EOF")