- name: Apply per-host commands
  hosts: all
  gather_facts: no
  vars:
    ansible_ssh_pipelining: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    commands_map:
      # insert a list of commands after each device

      #ch1:
        #- ip addr add 192.168.15.10/24 dev eth1
      #ch2:
        #- ip addr add 192.168.15.10/24 dev eth1
      #csw1:
        #- ip addr add 192.168.15.10/24 dev eth1
      #csw2:
        #- ip addr add 192.168.15.10/24 dev eth1
      #csw5:
        #- ip addr add 192.168.15.10/24 dev eth1
  tasks:
    - name: Run commands from commands_map
      become: yes
      become_user: gabripian
      become_method: sudo
      vars:
        cmds: "{{ commands_map[inventory_hostname] | default([]) | map('regex_replace', '^\\s*sudo\\s+', 'sudo -n ') | list}}"
      ansible.builtin.shell: |
        {% for c in cmds %}
        {{ c }}
        {% endfor %}
      when: commands_map[inventory_hostname] is defined and (commands_map[inventory_hostname] | length > 0)  
